import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import { Tiro_Devanagari_Marathi } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { cn } from "@/lib/utils";
import { FormProvider } from "./_context/store";
import { useState } from "react";
import { TemplateProvider } from "./_context/TemplateContext";
import { ImageProvider } from "./_context/ImageContext";

const inter = Tiro_Devanagari_Marathi({
  subsets: ["devanagari"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Unique Marathi Biodata Creator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>

      <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
<link href="https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400;1,600;1,700&family=Mukta:wght@200;300;400;500;600;700;800&family=Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900&display=swap" rel="stylesheet"/>
      </head>
      <body className={cn(inter.className, "#EAF0F1")}>
        <Navbar />
        <FormProvider>
          <TemplateProvider>
            <ImageProvider>
              <main className="w-full">{children}</main>
            </ImageProvider>
          </TemplateProvider>
        </FormProvider>
      </body>
    </html>
  );
}
